DROP TABLE word IF EXISTS;

CREATE TABLE word (
    id INT IDENTITY(1,1) PRIMARY KEY,
    deleted BIT NOT NULL DEFAULT 0,
    created DATETIME,
    modified DATETIME,
    value NVARCHAR(50) NOT NULL,
    chars NVARCHAR(50) NOT NULL,
    length INT NOT NULL
);

ALTER TABLE word ADD CONSTRAINT u_value UNIQUE(value);